controller_list:
  - name: fake_arm_controller
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_gripper_controller
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
  - name: fake_camera_controller
    joints:
      []
  - name: fake_base_controller
    joints:
      - caster_joint_bl
      - wheel_joint_bl
      - caster_joint_br
      - wheel_joint_br
      - caster_joint_fl
      - wheel_joint_fl
      - caster_joint_fr
      - wheel_joint_fr