<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       name="youbot" >
  
  <!-- The following xacro:included files set up definitions of parts of the robot body -->
  <!-- misc common stuff? -->
  <xacro:include filename="$(find youbot_description)/urdf/common.xacro" />

  <!-- youbot base -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_base/base.urdf.xacro" />

  <!-- youbot plate -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_plate/plate.urdf.xacro" /> 

  <!-- youbot arm -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_arm/arm.urdf.xacro"/>

  <!-- youbot gripper -->
  <xacro:include filename="$(find youbot_description)/urdf/youbot_gripper/gripper.urdf.xacro" />
 
  <!-- controller manager -->
  <xacro:include filename="$(find youbot_description)/controller/ros_controller.urdf.xacro" />
  
  <!-- materials for visualization -->
  <xacro:include filename="$(find youbot_description)/urdf/materials.urdf.xacro" />

  <!-- sensors -->
  <xacro:include filename="$(find sick_tim)/urdf/sick_tim.urdf.xacro" />
  <xacro:include filename="$(find youbot_description)/urdf/sensors/asus_xtion_camera.urdf.xacro" />
						     
  <!-- properties -->
  <property name="base_name" value="base"/>
  <property name="arm_name" value="arm"/>
  <property name="laser_name" value="laser"/>
  <property name="camera_name" value="camera"/>


  <!-- youbot base link and joint-->
<!--
  <link name="youbot_link" />
  <joint name="youbot_base_joint" type="fixed">
      <parent link="youbot_link" />
      <child link="${base_name}_footprint" />
  </joint>
-->
  <!-- youbot base files -->
  <xacro:youbot_base name="${base_name}"/>

  <xacro:youbot_plate name="plate" parent="${base_name}_link">
    <origin xyz="-0.159 0 0.046" rpy="0 0 0" />
  </xacro:youbot_plate>

  <xacro:youbot_arm name="${arm_name}" parent="${base_name}_link">
    <origin xyz="0.143 0 0.046" rpy="0 0 0" />
  </xacro:youbot_arm>

  <xacro:youbot_gripper name="gripper" parent="${arm_name}_link_5">
    <origin xyz="0 0 0" rpy="0 0 0" />
  </xacro:youbot_gripper>

  <!-- camera at the gripper -->
  <xacro:asus_xtion_camera name="${camera_name}" parent="${arm_name}_link_5" tilt="0" >
    <!-- <origin xyz="-0.035 0 0.015" rpy="0 -1.57 0" /> -->
    <origin xyz="-0.035 0 0.005" rpy="0 -1.57 0" />
  </xacro:asus_xtion_camera>

  <link name="camera_link" />
  <joint name="camera_link_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="${camera_name}_tilt_link" />
      <child link="camera_link" />
  </joint>

  <!-- base laser front -->
  <joint name="tim_mount_joint" type="fixed">
      <parent link="${base_name}_link" />
      <child link="${laser_name}_mount_link" />
      <origin xyz="${0.04+base_size_x/2.0} 0 0.01" rpy="3.14 0 0"/>
  </joint>
  <xacro:sick_tim551 name="${laser_name}" ros_topic="scan" />
  
</robot>
